# Server Configuration
server.port=8089
spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/assurance?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



# CORS Configuration
app.client.url=http://localhost:4200/

# Jackson Configuration
spring.jackson.stream-write-constraints.max-nesting-depth=200000 

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=isante.bot@gmail.com
spring.mail.password=Mohamed32@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true